doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                dbname: '%env(DATABASE_NAME)%'
                host: '%env(DATABASE_HOST)%'
                port: '%env(int:DATABASE_PORT)%'
                user: '%env(DATABASE_USERNAME)%'
                password: '%env(DATABASE_PASSWORD)%'
                driver: pdo_pgsql
                charset: utf8
                schema_filter: '~^(?!messenger_messages|lock_keys)~'
                options:
                    1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""))'
                use_savepoints: true
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                server_version: '14.2'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
