---
name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  validate-codebase:
    name: Validate codebase
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: main_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 5432
      DATABASE_USERNAME: app
      DATABASE_PASSWORD: app
      # config/packages/test/doctrine.yaml appends a "_test" suffix in the test env,
      # so this base name must match the "main_test" database created by the postgres service above.
      DATABASE_NAME: main

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Initialise repository
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock (app)
        working-directory: app
        run: composer validate --strict

      - name: Audit dependencies (app)
        working-directory: app
        run: composer audit --no-dev --locked

      - name: Cache Composer packages (app)
        id: composer-cache-app
        uses: actions/cache@v3
        with:
          path: app/vendor
          key: ${{ runner.os }}-php-app-${{ hashFiles('app/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-app-

      - name: Install dependencies (app)
        working-directory: app
        run: composer install --prefer-dist --no-progress

      - name: Cache Composer packages (tools)
        id: composer-cache-tools
        uses: actions/cache@v3
        with:
          path: tools/vendor
          key: ${{ runner.os }}-php-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-tools-

      - name: Install dependencies (tools)
        working-directory: tools
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        working-directory: tools
        run: php vendor/bin/phpstan --memory-limit=-1

      - name: Run PHP CS Fixer
        working-directory: tools
        run: PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer check

      - name: Run migrations
        working-directory: app
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Check Doctrine / DB scheme
        working-directory: app
        run: php bin/console doctrine:schema:validate -v --skip-sync --env=test

      - name: Load fixtures
        working-directory: app
        run: php bin/console hautelook:fixtures:load --no-interaction --env=test

      - name: Run PHPUnit
        working-directory: app
        run: php vendor/bin/phpunit
